defaults: &defaults
  dil_aware_detail_url: http://ansel.library.northwestern.edu/ImageServer/imageInfo.jsp?filename=/dimages/public/images/
  dil_aware_tile_url: http://ansel.library.northwestern.edu/ImageServer/tileServer?filename=/dimages/public/images/
  dil_fedora_disseminator: /inu:sdef-image/getWithLongSide?length=
  dil_fedora_disseminator_thumbnail: /inu:sdef-image/getWithLongSide?length=100
  dil_fedora_disseminator_collection: /inu:sdef-image/getWithLongSide?length=120
  dil_fedora_disseminator_ppt: /inu:sdef-image/getWithLongSide?length=500
  dil_uploads_collection: My Uploads
  dil_details_collection: My Details
  
development:  
   <<: *defaults
   dil_fedora_base_ip: 127.0.0.1
   dil_fedora_port: 8983
   dil_fedora_url: http://localhost:8983/fedora/get/
   dil_app_url: https://localhost:3000/
   dil_ppt_cgi_url: http://gandalf.library.northwestern.edu/cgi-bin/hydra/hydra-export-ppt-jms-test.cgi
   dil_upload_cgi_url: http://gandalf.library.northwestern.edu/cgi-bin/hydra/hydra-upload-test.cgi

test:  
   <<: *defaults
   dil_fedora_base_ip: 127.0.0.1
   dil_fedora_port: 8983
   dil_fedora_url: http://cecil.library.northwestern.edu:8983/fedora/get/
   dil_app_url: http://cecil.library.northwestern.edu:3000/
   dil_ppt_cgi_url: http://gandalf.library.northwestern.edu/cgi-bin/hydra/hydra-export-ppt-jms-test.cgi
   dil_upload_cgi_url: http://gandalf.library.northwestern.edu/cgi-bin/hydra/hydra-upload-test.cgi

production: 
   <<: *defaults
   dil_fedora_base_ip: repository.library.northwestern.edu
   dil_fedora_port: 80
   dil_fedora_url: http://repository.library.northwestern.edu/fedora/get/
   dil_app_url: http://emo.library.northwestern.edu/
   dil_ppt_cgi_url: http://gandalf.library.northwestern.edu/cgi-bin/hydra/hydra-export-ppt-jms.cgi
   dil_upload_cgi_url: http://gandalf.library.northwestern.edu/cgi-bin/hydra/hydra-upload.cgi
   